const nodemailer = require('nodemailer')

export default function handler(req, res) {
    var transport = nodemailer.createTransport({
        host: "smtp.gmail.com",
        port:  465,
        auth: {
          user: "2018-uam-1274@mnsuam.edu.pk", //generated by Mailtrap
          pass: "Letmelogin1!" //generated by Mailtrap
        }
      });
      var mailOptions = {
        from: '"Example Team" <from@example.com>',
        to: 'eprogrammer786@gmail.com',
        subject: 'Nice Nodemailer test',
        text: 'Hey there, it’s our first message sent with Nodemailer ;) ',
        html: '<b>Hey there! </b><br> This is our first message sent with Nodemailer',
        dsn: {
            id: 't1',
            return: 'headers',
            notify: 'success',
            recipient: 'eprogrammer786@gmail.com'
        }
    };
    transport.sendMail(mailOptions, (error, info) => {
        if (error) {
            return console.log(error);
        }
        console.log('Message sent: %s', info.messageId);
});
    res.status(200).json({ name: 'John Doe' })
  }
  