const nodemailer = require('nodemailer')

export default function handler(req, res) {
    let {to,body,title} = req.body
    var transport = nodemailer.createTransport({
        host: "smtp.gmail.com",
        port:  465,
        auth: {
          user: "2018-uam-1274@mnsuam.edu.pk", //generated by Mailtrap
          pass: "Letmelogin1!" //generated by Mailtrap
        }
      });
      var mailOptions = {
        from: '2018-uam-1274@mnsuam.edu.pk',
        to: to,
        subject: title,
        html: body,
        dsn: {
            id: 't1',
            return: 'headers',
            notify: 'success',
            recipient: 'eprogrammer786@gmail.com'
        }
    };
    transport.sendMail(mailOptions, (error, info) => {
        if (error) {
            return console.log(error);
        }
        console.log('Message sent: %s', info.messageId);
});
    res.status(200).json({ msg: 'sent' })
  }
  